
ALTER TABLE public.diagnoses
  ADD COLUMN IF NOT EXISTS height_cm INTEGER,
  ADD COLUMN IF NOT EXISTS weight_kg INTEGER,
  ADD COLUMN IF NOT EXISTS top_size TEXT,
  ADD COLUMN IF NOT EXISTS bottom_size TEXT,
  ADD COLUMN IF NOT EXISTS shoe_size TEXT,
  ADD COLUMN IF NOT EXISTS body_notes TEXT,
  ADD COLUMN IF NOT EXISTS hair_color TEXT,
  ADD COLUMN IF NOT EXISTS eye_color TEXT,
  ADD COLUMN IF NOT EXISTS skin_tone TEXT,
  ADD COLUMN IF NOT EXISTS fit_preference TEXT,
  ADD COLUMN IF NOT EXISTS formality_level TEXT,
  ADD COLUMN IF NOT EXISTS style_intensity_score JSONB,
  ADD COLUMN IF NOT EXISTS body_balance_score JSONB;
